import type { StaffAppointmentDTO, StaffWaitlistEntryDTO, SlotDTO } from "@/types";

export const staffAppointmentFixtures = {
	appointment: {
		id: "staff-appt-1",
		startsAt: "2026-05-10T10:00:00.000Z",
		endsAt: "2026-05-10T10:30:00.000Z",
		status: "CONFIRMED",
		createdAt: "2026-05-08T08:00:00.000Z",
		bookedByRole: "RECEPTIONIST",
		cancellationReason: null,
		patient: {
			id: "patient-1",
			firstName: "Amina",
			lastName: "Hassan",
			phone: "+966500000001",
			email: "amina@example.com",
		},
		doctor: {
			id: "doctor-1",
			firstName: "Nour",
			lastName: "Saleh",
			specialization: "General Dentistry",
		},
	} satisfies StaffAppointmentDTO,
	waitlistEntry: {
		id: "wait-1",
		position: 1,
		availableFrom: "09:00",
		availableUntil: "12:00",
		createdAt: "2026-05-08T08:15:00.000Z",
		patient: {
			id: "patient-2",
			firstName: "Sara",
			lastName: "Ali",
			phone: "+966500000002",
			email: "sara@example.com",
		},
		doctor: {
			id: "doctor-1",
			firstName: "Nour",
			lastName: "Saleh",
			specialization: "General Dentistry",
		},
	} satisfies StaffWaitlistEntryDTO,
	waitlistEntryTwo: {
		id: "wait-2",
		position: 2,
		availableFrom: null,
		availableUntil: null,
		createdAt: "2026-05-08T09:15:00.000Z",
		patient: {
			id: "patient-3",
			firstName: "Lina",
			lastName: "Omar",
			phone: "+966500000003",
			email: "lina@example.com",
		},
		doctor: {
			id: "doctor-2",
			firstName: "Maha",
			lastName: "Khalid",
			specialization: "Pediatric Dentistry",
		},
	} satisfies StaffWaitlistEntryDTO,
	waitlistEntryPageTwo: {
		id: "wait-3",
		position: 11,
		availableFrom: "14:00",
		availableUntil: "16:00",
		createdAt: "2026-05-08T10:15:00.000Z",
		patient: {
			id: "patient-4",
			firstName: "Omar",
			lastName: "Yousef",
			phone: "+966500000004",
			email: "omar@example.com",
		},
		doctor: {
			id: "doctor-2",
			firstName: "Maha",
			lastName: "Khalid",
			specialization: "Pediatric Dentistry",
		},
	} satisfies StaffWaitlistEntryDTO,
	waitlistPage: {
		data: [
			{
				id: "wait-1",
				position: 1,
				availableFrom: "09:00",
				availableUntil: "12:00",
				createdAt: "2026-05-08T08:15:00.000Z",
				patient: {
					id: "patient-2",
					firstName: "Sara",
					lastName: "Ali",
					phone: "+966500000002",
					email: "sara@example.com",
				},
				doctor: {
					id: "doctor-1",
					firstName: "Nour",
					lastName: "Saleh",
					specialization: "General Dentistry",
				},
			},
		],
		total: 1,
		page: 1,
		pageSize: 10,
	},
	waitlistPageTwo: {
		data: [
			{
				id: "wait-3",
				position: 11,
				availableFrom: "14:00",
				availableUntil: "16:00",
				createdAt: "2026-05-08T10:15:00.000Z",
				patient: {
					id: "patient-4",
					firstName: "Omar",
					lastName: "Yousef",
					phone: "+966500000004",
					email: "omar@example.com",
				},
				doctor: {
					id: "doctor-2",
					firstName: "Maha",
					lastName: "Khalid",
					specialization: "Pediatric Dentistry",
				},
			},
		],
		total: 11,
		page: 2,
		pageSize: 10,
	},
	waitlistPageEmpty: {
		data: [],
		total: 0,
		page: 1,
		pageSize: 10,
	},
	slot: {
		startsAt: "2026-05-10T11:00:00.000Z",
		endsAt: "2026-05-10T11:30:00.000Z",
		doctorId: "doctor-1",
	} satisfies SlotDTO,
};
