/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as R403RouteImport } from './routes/403'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LobbyDoctorIdRouteImport } from './routes/lobby.$doctorId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedReceptionistRouteImport } from './routes/_authenticated._receptionist'
import { Route as AuthenticatedPatientRouteImport } from './routes/_authenticated._patient'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated._doctor'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated._admin'
import { Route as AuthenticatedPatientWaitlistRouteImport } from './routes/_authenticated._patient.waitlist'
import { Route as AuthenticatedPatientMyAppointmentsRouteImport } from './routes/_authenticated._patient.my-appointments'
import { Route as AuthenticatedPatientBookRouteImport } from './routes/_authenticated._patient.book'
import { Route as AuthenticatedReceptionistStaffWalkInRouteImport } from './routes/_authenticated._receptionist.staff.walk-in'
import { Route as AuthenticatedReceptionistStaffQueueRouteImport } from './routes/_authenticated._receptionist.staff.queue'
import { Route as AuthenticatedReceptionistStaffPatientsRouteImport } from './routes/_authenticated._receptionist.staff.patients'
import { Route as AuthenticatedReceptionistStaffLobbyAccessRouteImport } from './routes/_authenticated._receptionist.staff.lobby-access'
import { Route as AuthenticatedReceptionistStaffAppointmentsRouteImport } from './routes/_authenticated._receptionist.staff.appointments'
import { Route as AuthenticatedPatientOffersSplatRouteImport } from './routes/_authenticated._patient.offers.$'
import { Route as AuthenticatedDoctorDoctorTodayRouteImport } from './routes/_authenticated._doctor.doctor.today'
import { Route as AuthenticatedDoctorDoctorScheduleRouteImport } from './routes/_authenticated._doctor.doctor.schedule'
import { Route as AuthenticatedDoctorDoctorQueueRouteImport } from './routes/_authenticated._doctor.doctor.queue'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated._admin.admin.users'
import { Route as AuthenticatedAdminAdminUserSettingsRouteImport } from './routes/_authenticated._admin.admin.user-settings'
import { Route as AuthenticatedAdminAdminSettingsRouteImport } from './routes/_authenticated._admin.admin.settings'
import { Route as AuthenticatedAdminAdminLobbyAccessRouteImport } from './routes/_authenticated._admin.admin.lobby-access'
import { Route as AuthenticatedAdminAdminDoctorsRouteImport } from './routes/_authenticated._admin.admin.doctors'
import { Route as AuthenticatedAdminAdminDashboardRouteImport } from './routes/_authenticated._admin.admin.dashboard'
import { Route as AuthenticatedAdminAdminAuditRouteImport } from './routes/_authenticated._admin.admin.audit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyDoctorIdRoute = LobbyDoctorIdRouteImport.update({
  id: '/lobby/$doctorId',
  path: '/lobby/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReceptionistRoute =
  AuthenticatedReceptionistRouteImport.update({
    id: '/_receptionist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientRoute = AuthenticatedPatientRouteImport.update({
  id: '/_patient',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/_doctor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientWaitlistRoute =
  AuthenticatedPatientWaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientMyAppointmentsRoute =
  AuthenticatedPatientMyAppointmentsRouteImport.update({
    id: '/my-appointments',
    path: '/my-appointments',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientBookRoute =
  AuthenticatedPatientBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedReceptionistStaffWalkInRoute =
  AuthenticatedReceptionistStaffWalkInRouteImport.update({
    id: '/staff/walk-in',
    path: '/staff/walk-in',
    getParentRoute: () => AuthenticatedReceptionistRoute,
  } as any)
const AuthenticatedReceptionistStaffQueueRoute =
  AuthenticatedReceptionistStaffQueueRouteImport.update({
    id: '/staff/queue',
    path: '/staff/queue',
    getParentRoute: () => AuthenticatedReceptionistRoute,
  } as any)
const AuthenticatedReceptionistStaffPatientsRoute =
  AuthenticatedReceptionistStaffPatientsRouteImport.update({
    id: '/staff/patients',
    path: '/staff/patients',
    getParentRoute: () => AuthenticatedReceptionistRoute,
  } as any)
const AuthenticatedReceptionistStaffLobbyAccessRoute =
  AuthenticatedReceptionistStaffLobbyAccessRouteImport.update({
    id: '/staff/lobby-access',
    path: '/staff/lobby-access',
    getParentRoute: () => AuthenticatedReceptionistRoute,
  } as any)
const AuthenticatedReceptionistStaffAppointmentsRoute =
  AuthenticatedReceptionistStaffAppointmentsRouteImport.update({
    id: '/staff/appointments',
    path: '/staff/appointments',
    getParentRoute: () => AuthenticatedReceptionistRoute,
  } as any)
const AuthenticatedPatientOffersSplatRoute =
  AuthenticatedPatientOffersSplatRouteImport.update({
    id: '/offers/$',
    path: '/offers/$',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedDoctorDoctorTodayRoute =
  AuthenticatedDoctorDoctorTodayRouteImport.update({
    id: '/doctor/today',
    path: '/doctor/today',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorDoctorScheduleRoute =
  AuthenticatedDoctorDoctorScheduleRouteImport.update({
    id: '/doctor/schedule',
    path: '/doctor/schedule',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorDoctorQueueRoute =
  AuthenticatedDoctorDoctorQueueRouteImport.update({
    id: '/doctor/queue',
    path: '/doctor/queue',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminUserSettingsRoute =
  AuthenticatedAdminAdminUserSettingsRouteImport.update({
    id: '/admin/user-settings',
    path: '/admin/user-settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSettingsRoute =
  AuthenticatedAdminAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminLobbyAccessRoute =
  AuthenticatedAdminAdminLobbyAccessRouteImport.update({
    id: '/admin/lobby-access',
    path: '/admin/lobby-access',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminDoctorsRoute =
  AuthenticatedAdminAdminDoctorsRouteImport.update({
    id: '/admin/doctors',
    path: '/admin/doctors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminDashboardRoute =
  AuthenticatedAdminAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAuditRoute =
  AuthenticatedAdminAdminAuditRouteImport.update({
    id: '/admin/audit',
    path: '/admin/audit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/lobby/$doctorId': typeof LobbyDoctorIdRoute
  '/book': typeof AuthenticatedPatientBookRoute
  '/my-appointments': typeof AuthenticatedPatientMyAppointmentsRoute
  '/waitlist': typeof AuthenticatedPatientWaitlistRoute
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/dashboard': typeof AuthenticatedAdminAdminDashboardRoute
  '/admin/doctors': typeof AuthenticatedAdminAdminDoctorsRoute
  '/admin/lobby-access': typeof AuthenticatedAdminAdminLobbyAccessRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/user-settings': typeof AuthenticatedAdminAdminUserSettingsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/doctor/queue': typeof AuthenticatedDoctorDoctorQueueRoute
  '/doctor/schedule': typeof AuthenticatedDoctorDoctorScheduleRoute
  '/doctor/today': typeof AuthenticatedDoctorDoctorTodayRoute
  '/offers/$': typeof AuthenticatedPatientOffersSplatRoute
  '/staff/appointments': typeof AuthenticatedReceptionistStaffAppointmentsRoute
  '/staff/lobby-access': typeof AuthenticatedReceptionistStaffLobbyAccessRoute
  '/staff/patients': typeof AuthenticatedReceptionistStaffPatientsRoute
  '/staff/queue': typeof AuthenticatedReceptionistStaffQueueRoute
  '/staff/walk-in': typeof AuthenticatedReceptionistStaffWalkInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/lobby/$doctorId': typeof LobbyDoctorIdRoute
  '/book': typeof AuthenticatedPatientBookRoute
  '/my-appointments': typeof AuthenticatedPatientMyAppointmentsRoute
  '/waitlist': typeof AuthenticatedPatientWaitlistRoute
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/dashboard': typeof AuthenticatedAdminAdminDashboardRoute
  '/admin/doctors': typeof AuthenticatedAdminAdminDoctorsRoute
  '/admin/lobby-access': typeof AuthenticatedAdminAdminLobbyAccessRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/user-settings': typeof AuthenticatedAdminAdminUserSettingsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/doctor/queue': typeof AuthenticatedDoctorDoctorQueueRoute
  '/doctor/schedule': typeof AuthenticatedDoctorDoctorScheduleRoute
  '/doctor/today': typeof AuthenticatedDoctorDoctorTodayRoute
  '/offers/$': typeof AuthenticatedPatientOffersSplatRoute
  '/staff/appointments': typeof AuthenticatedReceptionistStaffAppointmentsRoute
  '/staff/lobby-access': typeof AuthenticatedReceptionistStaffLobbyAccessRoute
  '/staff/patients': typeof AuthenticatedReceptionistStaffPatientsRoute
  '/staff/queue': typeof AuthenticatedReceptionistStaffQueueRoute
  '/staff/walk-in': typeof AuthenticatedReceptionistStaffWalkInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/_authenticated/_patient': typeof AuthenticatedPatientRouteWithChildren
  '/_authenticated/_receptionist': typeof AuthenticatedReceptionistRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/lobby/$doctorId': typeof LobbyDoctorIdRoute
  '/_authenticated/_patient/book': typeof AuthenticatedPatientBookRoute
  '/_authenticated/_patient/my-appointments': typeof AuthenticatedPatientMyAppointmentsRoute
  '/_authenticated/_patient/waitlist': typeof AuthenticatedPatientWaitlistRoute
  '/_authenticated/_admin/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/_authenticated/_admin/admin/dashboard': typeof AuthenticatedAdminAdminDashboardRoute
  '/_authenticated/_admin/admin/doctors': typeof AuthenticatedAdminAdminDoctorsRoute
  '/_authenticated/_admin/admin/lobby-access': typeof AuthenticatedAdminAdminLobbyAccessRoute
  '/_authenticated/_admin/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/_authenticated/_admin/admin/user-settings': typeof AuthenticatedAdminAdminUserSettingsRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/_doctor/doctor/queue': typeof AuthenticatedDoctorDoctorQueueRoute
  '/_authenticated/_doctor/doctor/schedule': typeof AuthenticatedDoctorDoctorScheduleRoute
  '/_authenticated/_doctor/doctor/today': typeof AuthenticatedDoctorDoctorTodayRoute
  '/_authenticated/_patient/offers/$': typeof AuthenticatedPatientOffersSplatRoute
  '/_authenticated/_receptionist/staff/appointments': typeof AuthenticatedReceptionistStaffAppointmentsRoute
  '/_authenticated/_receptionist/staff/lobby-access': typeof AuthenticatedReceptionistStaffLobbyAccessRoute
  '/_authenticated/_receptionist/staff/patients': typeof AuthenticatedReceptionistStaffPatientsRoute
  '/_authenticated/_receptionist/staff/queue': typeof AuthenticatedReceptionistStaffQueueRoute
  '/_authenticated/_receptionist/staff/walk-in': typeof AuthenticatedReceptionistStaffWalkInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/403'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/profile'
    | '/lobby/$doctorId'
    | '/book'
    | '/my-appointments'
    | '/waitlist'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/lobby-access'
    | '/admin/settings'
    | '/admin/user-settings'
    | '/admin/users'
    | '/doctor/queue'
    | '/doctor/schedule'
    | '/doctor/today'
    | '/offers/$'
    | '/staff/appointments'
    | '/staff/lobby-access'
    | '/staff/patients'
    | '/staff/queue'
    | '/staff/walk-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/403'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/profile'
    | '/lobby/$doctorId'
    | '/book'
    | '/my-appointments'
    | '/waitlist'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/lobby-access'
    | '/admin/settings'
    | '/admin/user-settings'
    | '/admin/users'
    | '/doctor/queue'
    | '/doctor/schedule'
    | '/doctor/today'
    | '/offers/$'
    | '/staff/appointments'
    | '/staff/lobby-access'
    | '/staff/patients'
    | '/staff/queue'
    | '/staff/walk-in'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/403'
    | '/_authenticated'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/_admin'
    | '/_authenticated/_doctor'
    | '/_authenticated/_patient'
    | '/_authenticated/_receptionist'
    | '/_authenticated/profile'
    | '/lobby/$doctorId'
    | '/_authenticated/_patient/book'
    | '/_authenticated/_patient/my-appointments'
    | '/_authenticated/_patient/waitlist'
    | '/_authenticated/_admin/admin/audit'
    | '/_authenticated/_admin/admin/dashboard'
    | '/_authenticated/_admin/admin/doctors'
    | '/_authenticated/_admin/admin/lobby-access'
    | '/_authenticated/_admin/admin/settings'
    | '/_authenticated/_admin/admin/user-settings'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_doctor/doctor/queue'
    | '/_authenticated/_doctor/doctor/schedule'
    | '/_authenticated/_doctor/doctor/today'
    | '/_authenticated/_patient/offers/$'
    | '/_authenticated/_receptionist/staff/appointments'
    | '/_authenticated/_receptionist/staff/lobby-access'
    | '/_authenticated/_receptionist/staff/patients'
    | '/_authenticated/_receptionist/staff/queue'
    | '/_authenticated/_receptionist/staff/walk-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R403Route: typeof R403Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LobbyDoctorIdRoute: typeof LobbyDoctorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$doctorId': {
      id: '/lobby/$doctorId'
      path: '/lobby/$doctorId'
      fullPath: '/lobby/$doctorId'
      preLoaderRoute: typeof LobbyDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_receptionist': {
      id: '/_authenticated/_receptionist'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedReceptionistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_patient': {
      id: '/_authenticated/_patient'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedPatientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_doctor': {
      id: '/_authenticated/_doctor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_patient/waitlist': {
      id: '/_authenticated/_patient/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof AuthenticatedPatientWaitlistRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/_patient/my-appointments': {
      id: '/_authenticated/_patient/my-appointments'
      path: '/my-appointments'
      fullPath: '/my-appointments'
      preLoaderRoute: typeof AuthenticatedPatientMyAppointmentsRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/_patient/book': {
      id: '/_authenticated/_patient/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AuthenticatedPatientBookRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/_receptionist/staff/walk-in': {
      id: '/_authenticated/_receptionist/staff/walk-in'
      path: '/staff/walk-in'
      fullPath: '/staff/walk-in'
      preLoaderRoute: typeof AuthenticatedReceptionistStaffWalkInRouteImport
      parentRoute: typeof AuthenticatedReceptionistRoute
    }
    '/_authenticated/_receptionist/staff/queue': {
      id: '/_authenticated/_receptionist/staff/queue'
      path: '/staff/queue'
      fullPath: '/staff/queue'
      preLoaderRoute: typeof AuthenticatedReceptionistStaffQueueRouteImport
      parentRoute: typeof AuthenticatedReceptionistRoute
    }
    '/_authenticated/_receptionist/staff/patients': {
      id: '/_authenticated/_receptionist/staff/patients'
      path: '/staff/patients'
      fullPath: '/staff/patients'
      preLoaderRoute: typeof AuthenticatedReceptionistStaffPatientsRouteImport
      parentRoute: typeof AuthenticatedReceptionistRoute
    }
    '/_authenticated/_receptionist/staff/lobby-access': {
      id: '/_authenticated/_receptionist/staff/lobby-access'
      path: '/staff/lobby-access'
      fullPath: '/staff/lobby-access'
      preLoaderRoute: typeof AuthenticatedReceptionistStaffLobbyAccessRouteImport
      parentRoute: typeof AuthenticatedReceptionistRoute
    }
    '/_authenticated/_receptionist/staff/appointments': {
      id: '/_authenticated/_receptionist/staff/appointments'
      path: '/staff/appointments'
      fullPath: '/staff/appointments'
      preLoaderRoute: typeof AuthenticatedReceptionistStaffAppointmentsRouteImport
      parentRoute: typeof AuthenticatedReceptionistRoute
    }
    '/_authenticated/_patient/offers/$': {
      id: '/_authenticated/_patient/offers/$'
      path: '/offers/$'
      fullPath: '/offers/$'
      preLoaderRoute: typeof AuthenticatedPatientOffersSplatRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/_doctor/doctor/today': {
      id: '/_authenticated/_doctor/doctor/today'
      path: '/doctor/today'
      fullPath: '/doctor/today'
      preLoaderRoute: typeof AuthenticatedDoctorDoctorTodayRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/_doctor/doctor/schedule': {
      id: '/_authenticated/_doctor/doctor/schedule'
      path: '/doctor/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof AuthenticatedDoctorDoctorScheduleRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/_doctor/doctor/queue': {
      id: '/_authenticated/_doctor/doctor/queue'
      path: '/doctor/queue'
      fullPath: '/doctor/queue'
      preLoaderRoute: typeof AuthenticatedDoctorDoctorQueueRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/user-settings': {
      id: '/_authenticated/_admin/admin/user-settings'
      path: '/admin/user-settings'
      fullPath: '/admin/user-settings'
      preLoaderRoute: typeof AuthenticatedAdminAdminUserSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/settings': {
      id: '/_authenticated/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/lobby-access': {
      id: '/_authenticated/_admin/admin/lobby-access'
      path: '/admin/lobby-access'
      fullPath: '/admin/lobby-access'
      preLoaderRoute: typeof AuthenticatedAdminAdminLobbyAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/doctors': {
      id: '/_authenticated/_admin/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AuthenticatedAdminAdminDoctorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/dashboard': {
      id: '/_authenticated/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/audit': {
      id: '/_authenticated/_admin/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminAuditRoute: typeof AuthenticatedAdminAdminAuditRoute
  AuthenticatedAdminAdminDashboardRoute: typeof AuthenticatedAdminAdminDashboardRoute
  AuthenticatedAdminAdminDoctorsRoute: typeof AuthenticatedAdminAdminDoctorsRoute
  AuthenticatedAdminAdminLobbyAccessRoute: typeof AuthenticatedAdminAdminLobbyAccessRoute
  AuthenticatedAdminAdminSettingsRoute: typeof AuthenticatedAdminAdminSettingsRoute
  AuthenticatedAdminAdminUserSettingsRoute: typeof AuthenticatedAdminAdminUserSettingsRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminAuditRoute: AuthenticatedAdminAdminAuditRoute,
  AuthenticatedAdminAdminDashboardRoute: AuthenticatedAdminAdminDashboardRoute,
  AuthenticatedAdminAdminDoctorsRoute: AuthenticatedAdminAdminDoctorsRoute,
  AuthenticatedAdminAdminLobbyAccessRoute:
    AuthenticatedAdminAdminLobbyAccessRoute,
  AuthenticatedAdminAdminSettingsRoute: AuthenticatedAdminAdminSettingsRoute,
  AuthenticatedAdminAdminUserSettingsRoute:
    AuthenticatedAdminAdminUserSettingsRoute,
  AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDoctorRouteChildren {
  AuthenticatedDoctorDoctorQueueRoute: typeof AuthenticatedDoctorDoctorQueueRoute
  AuthenticatedDoctorDoctorScheduleRoute: typeof AuthenticatedDoctorDoctorScheduleRoute
  AuthenticatedDoctorDoctorTodayRoute: typeof AuthenticatedDoctorDoctorTodayRoute
}

const AuthenticatedDoctorRouteChildren: AuthenticatedDoctorRouteChildren = {
  AuthenticatedDoctorDoctorQueueRoute: AuthenticatedDoctorDoctorQueueRoute,
  AuthenticatedDoctorDoctorScheduleRoute:
    AuthenticatedDoctorDoctorScheduleRoute,
  AuthenticatedDoctorDoctorTodayRoute: AuthenticatedDoctorDoctorTodayRoute,
}

const AuthenticatedDoctorRouteWithChildren =
  AuthenticatedDoctorRoute._addFileChildren(AuthenticatedDoctorRouteChildren)

interface AuthenticatedPatientRouteChildren {
  AuthenticatedPatientBookRoute: typeof AuthenticatedPatientBookRoute
  AuthenticatedPatientMyAppointmentsRoute: typeof AuthenticatedPatientMyAppointmentsRoute
  AuthenticatedPatientWaitlistRoute: typeof AuthenticatedPatientWaitlistRoute
  AuthenticatedPatientOffersSplatRoute: typeof AuthenticatedPatientOffersSplatRoute
}

const AuthenticatedPatientRouteChildren: AuthenticatedPatientRouteChildren = {
  AuthenticatedPatientBookRoute: AuthenticatedPatientBookRoute,
  AuthenticatedPatientMyAppointmentsRoute:
    AuthenticatedPatientMyAppointmentsRoute,
  AuthenticatedPatientWaitlistRoute: AuthenticatedPatientWaitlistRoute,
  AuthenticatedPatientOffersSplatRoute: AuthenticatedPatientOffersSplatRoute,
}

const AuthenticatedPatientRouteWithChildren =
  AuthenticatedPatientRoute._addFileChildren(AuthenticatedPatientRouteChildren)

interface AuthenticatedReceptionistRouteChildren {
  AuthenticatedReceptionistStaffAppointmentsRoute: typeof AuthenticatedReceptionistStaffAppointmentsRoute
  AuthenticatedReceptionistStaffLobbyAccessRoute: typeof AuthenticatedReceptionistStaffLobbyAccessRoute
  AuthenticatedReceptionistStaffPatientsRoute: typeof AuthenticatedReceptionistStaffPatientsRoute
  AuthenticatedReceptionistStaffQueueRoute: typeof AuthenticatedReceptionistStaffQueueRoute
  AuthenticatedReceptionistStaffWalkInRoute: typeof AuthenticatedReceptionistStaffWalkInRoute
}

const AuthenticatedReceptionistRouteChildren: AuthenticatedReceptionistRouteChildren =
  {
    AuthenticatedReceptionistStaffAppointmentsRoute:
      AuthenticatedReceptionistStaffAppointmentsRoute,
    AuthenticatedReceptionistStaffLobbyAccessRoute:
      AuthenticatedReceptionistStaffLobbyAccessRoute,
    AuthenticatedReceptionistStaffPatientsRoute:
      AuthenticatedReceptionistStaffPatientsRoute,
    AuthenticatedReceptionistStaffQueueRoute:
      AuthenticatedReceptionistStaffQueueRoute,
    AuthenticatedReceptionistStaffWalkInRoute:
      AuthenticatedReceptionistStaffWalkInRoute,
  }

const AuthenticatedReceptionistRouteWithChildren =
  AuthenticatedReceptionistRoute._addFileChildren(
    AuthenticatedReceptionistRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRouteWithChildren
  AuthenticatedPatientRoute: typeof AuthenticatedPatientRouteWithChildren
  AuthenticatedReceptionistRoute: typeof AuthenticatedReceptionistRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRouteWithChildren,
  AuthenticatedPatientRoute: AuthenticatedPatientRouteWithChildren,
  AuthenticatedReceptionistRoute: AuthenticatedReceptionistRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R403Route: R403Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LobbyDoctorIdRoute: LobbyDoctorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
